PropertyRentalManagement/Controllers/BuildingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PropertyRentalManagement.Data;
using PropertyRentalManagement.Models;

namespace PropertyRentalManagement.Controllers
{
    [Authorize(Roles = "Owner,Administrator, Manager")]
    public class BuildingsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public BuildingsController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        // GET: Buildings
        public async Task<IActionResult> Index()
        {
            if (TempData.ContainsKey("ErrorMessage"))
            {
                ViewBag.ErrorMessage = TempData["ErrorMessage"];
            }

            return View(_context.Buildings.Include(b => b.PropertyOwner).ToList());
        }

        // GET: Buildings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var building = await _context.Buildings
                .Include(b => b.PropertyOwner)
                .FirstOrDefaultAsync(m => m.BuildingId == id);
            if (building == null)
            {
                return NotFound();
            }

            return View(building);
        }

        // GET: Buildings/Create
        public async Task<IActionResult> CreateAsync()
        {
            var owners = await _userManager.GetUsersInRoleAsync("Owner");

            ViewData["PropertyOwnerId"] = new SelectList(owners, "Id", "UserName");

            return View();
        }

        // POST: Buildings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BuildingId,Name,Address,Description,PropertyOwnerId")] Building building)
        {
            if (ModelState.IsValid)
            {
                _context.Add(building);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            var owners = await _userManager.GetUsersInRoleAsync("Owner");

            ViewData["PropertyOwnerId"] = new SelectList(owners, "Id", "UserName", building.PropertyOwnerId);
            return View(building);
        }

        // GET: Buildings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var building = await _context.Buildings.FindAsync(id);
            if (building == null)
            {
                return NotFound();
            }
            var owners = await _userManager.GetUsersInRoleAsync("Owner");

            ViewData["PropertyOwnerId"] = new SelectList(owners, "Id", "UserName", building.PropertyOwnerId);
            return View(building);
        }

        // POST: Buildings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BuildingId,Name,Address,Description,PropertyOwnerId")] Building building)
        {

            if (id != building.BuildingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(building);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BuildingExists(building.BuildingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            var owners = await _userManager.GetUsersInRoleAsync("Owner");

            ViewData["PropertyOwnerId"] = new SelectList(owners, "Id", "UserName", building.PropertyOwnerId);
            return View(building);
        }

        // GET: Buildings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var building = await _context.Buildings
                .Include(b => b.PropertyOwner)
                .FirstOrDefaultAsync(m => m.BuildingId == id);
            if (building == null)
            {
                return NotFound();
            }

            return View(building);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Check if the building has any associated apartments
            if (BuildingHasApartments(id))
            {
                TempData["ErrorMessage"] = "Cannot delete building with associated apartments. Delete all apartment belong to this building before delete it.";
                return RedirectToAction(nameof(Index));
            }

            var building = await _context.Buildings.FindAsync(id);
            if (building != null)
            {
                _context.Buildings.Remove(building);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool BuildingHasApartments(int buildingId)
        {
            // Check if the building has any associated apartments
            return _context.Apartments.Any(a => a.BuildingId == buildingId);
        }

        private bool BuildingExists(int id)
        {
            return _context.Buildings.Any(e => e.BuildingId == id);
        }


    }
}

PropertyRentalManagement/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PropertyRentalManagement.Data;
using PropertyRentalManagement.Models;

namespace PropertyRentalManagement.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public MessagesController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Messages
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);

            //// Count unread messages for the current user
            //var unreadMessagesCount = await CountUnreadMessages(userId);

            //// Pass the count to the view
            //ViewBag.UnreadMessagesCount = unreadMessagesCount;

            var appDbContext = _context.Messages
                .Include(m => m.ReadStatus)
                .Include(m => m.Receiver)
                .Include(m => m.Sender)
                .Where(m => m.SenderId == userId || m.ReceiverId == userId);

            return View(await appDbContext.ToListAsync());
        }

     



        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .Include(m => m.ReadStatus)
                .Include(m => m.Receiver)
                .Include(m => m.Sender)
                .FirstOrDefaultAsync(m => m.MessageId == id);

            if (message == null)
            {
                return NotFound();
            }

            // Check if the current user is the receiver of the message
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser != null && message.ReceiverId == currentUser.Id)
            {
                // Set the message status to "Read" if the current user is the receiver
                message.ReadStatus = _context.Statuses.FirstOrDefault(s => s.Description == "Read");

                // Update the database
                await _context.SaveChangesAsync();
            }

            return View(message);
        }


        // GET: Messages/Create
        public IActionResult Create()
        {
            var sender = _userManager.GetUserName(User); // Get the ID of the current logged-in user

            // Set default values for other properties
            ViewData["ReadStatusId"] = "Unread"; // Set the default value for ReadStatusId
            ViewData["ReceiverId"] = new SelectList(_context.AppUsers, "Id", "UserName");

            // Create a list with a single SelectListItem representing the sender
            var senderList = new List<SelectListItem>
    {
        new SelectListItem { Value = sender, Text = sender }
    };

            // Set the SenderId using the list
            ViewData["SenderId"] = new SelectList(senderList, "Value", "Text");

            return View();
        }


        // POST: Messages/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MessageId,SenderId,ReceiverId,MessageContent,Timestamp,ReadStatusId")] Message message)
        {
            if (ModelState.IsValid)
            {
                message.SenderId = _userManager.GetUserId(User); // Set the ID of the current logged-in user as the sender
                message.Timestamp = DateTime.Now; // Set the Timestamp to the current time
                var status = await _context.Statuses.FirstOrDefaultAsync(s => s.Description.Equals("Unread")); ;
                message.ReadStatusId = status.StatusId;
                _context.Add(message);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Set default values for other properties
            ViewData["ReadStatusId"] = "Unread";
            ViewData["ReceiverId"] = new SelectList(_context.AppUsers, "Id", "UserName", message.ReceiverId);

            // You can directly set the SenderId without using SelectList
            ViewData["SenderId"] = message.SenderId;

            return View(message);
        }






        // GET: Messages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages.FindAsync(id);
            if (message == null)
            {
                return NotFound();
            }
            ViewData["ReadStatusId"] = new SelectList(_context.Statuses, "StatusId", "Description", message.ReadStatusId);
            ViewData["ReceiverId"] = new SelectList(_context.AppUsers, "Id", "UserName", message.ReceiverId);
            ViewData["SenderId"] = new SelectList(_context.AppUsers, "Id", "UserName", message.SenderId);
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MessageId,SenderId,ReceiverId,MessageContent,Timestamp,ReadStatusId")] Message message)
        {
            if (id != message.MessageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    
                    _context.Update(message);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MessageExists(message.MessageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ReadStatusId"] = new SelectList(_context.Statuses, "StatusId", "Description", message.ReadStatusId);
            ViewData["ReceiverId"] = new SelectList(_context.AppUsers, "Id", "UserName", message.ReceiverId);
            ViewData["SenderId"] = new SelectList(_context.AppUsers, "Id", "UserName", message.SenderId);
            return View(message);
        }

        // GET: Messages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .Include(m => m.ReadStatus)
                .Include(m => m.Receiver)
                .Include(m => m.Sender)
                .FirstOrDefaultAsync(m => m.MessageId == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var message = await _context.Messages.FindAsync(id);
            if (message != null)
            {
                _context.Messages.Remove(message);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MessageExists(int id)
        {
            return _context.Messages.Any(e => e.MessageId == id);
        }
        

    }
}

PropertyRentalManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PropertyRentalManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PropertyRentalManagement.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand border-bottom box-shadow mb-4" style="background-color:darkslategrey">
            <div class="container-fluid">
                <img class="me-4 ms-4" src="~/logo.png" height="40" />
                <a class="navbar-brand text-primary" asp-area="" asp-controller="Home" asp-action="Index">Property Rental Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Apartments" asp-action="Index">Apartment</a>
                        </li>
                        @if (User.IsInRole("Owner") || User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="UserRoles" asp-action="Index">Account</a>
                            </li>
                        }
                        @if (User.IsInRole("Manager") || User.IsInRole("Administrator")|| User.IsInRole("Owner"))
                        {
                           
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Buildings" asp-action="Index">Building</a>
                            </li>
                           
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Appointments" asp-action="Index">Appointment</a>
                            </li>
                        }
                      

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Messages" asp-action="Index">Message</a>
                            </li>

                            @if (ViewData["UnreadMessagesCount"] != null)
                            {
                                var unReadMessages = (int)@ViewData["UnreadMessagesCount"];
                                <div>
                                    <a asp-action="Login">
                                        <span>@unReadMessages</span>
                                    </a>
                                </div>
                            }
                        }


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PropertyRentalManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>